### PR TITLE
Remove margin between file input field and link

### PR DESCRIPTION
**Pull request by dontub**
The file input field is wrapped by a `div` with class `.form-item` and thus gets a bottom margin. The `p` element containing the link to the current file has a top margin. So there is a lot of space between input field and link. This change sets these margins to `0`.

systopia-reference: 25904

### CODE REVIEW

**Comment by jensschuppe** [comment]
@dontub can you show the relevant part of the DOM (e.g. screenshot)? Maybe using `#field_prefix` instead of `#prefix` might be an option for not requiring additional CSS …

**Comment by dontub** [comment]
The resulting HTML is like this:
```html
<div class="js-form-item form-item custom-control custom-file js-form-type-file form-type-file js-form-item-files-foo form-item-files-foo">
	<label for="edit-foo" class="custom-control-label">Foo</label>
	<div class="wrapper-input-file">
		<input data-drupal-selector="edit-foo" type="file" id="edit-foo" name="files[foo]" size="60" class="js-form-file form-file">
		<label for="file">Choose a file</label>
	</div>
</div>
<p class="civiremote-form-file-link">
  <a href="url/to/foo.txt" target="_blank" data-drupal-selector="edit-link" id="edit-link">foo.txt</a>
</p>
```

The element of type `link` is a `RenderElement` not a `FormElement` so there's no `#field_prefix`. Maybe I don't understand your idea...

**Comment by jensschuppe** [comment]
I thought of placing the link as `#field_prefix` (or rather `#field_suffix`) of the `file` form element. But I think tose only support plain text. Maybe the link can be placed in the `file` element's `#suffix`? The point is that the link would be inside the form element wrapper and thus not subject to its margins.

**Comment by dontub** [comment]
`#suffix` has to be a string, too. https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21RenderElementBase.php/class/RenderElementBase/11.x

Yet, it would be preferable if the link would be inside the form element wrapper.

**Comment by jensschuppe** [comment]
I think the "proper" thing to do would be creating a new render element, containing and processing both elements (the file upload field and a link element for the current file). Not sure however whether it's worth the effort only for a margin …

**Comment by dontub** [comment]
I've created an issue for this #40 and I'll merge this now.

**Pull request merged**
